# Taller 2b Matriz inversa - descomposición LU

Estudiante: Anthony Alangasí

Grupo: GR1CC

Fecha: 13/01/2026

Haga modificaciones a las funciones base del siguiente código:
https://github.com/ztjona/MN-prueba-02/tree/main
para encontrar la matriz inversa de las siguientes matrices:

In [7]:
A_1 = [[1,3,4],[2,1,3],[4,2,1]]

In [8]:
import logging
from sys import stdout
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())


import numpy as np

# ####################################################################
def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante el método de eliminación gaussiana.

    ## Parameters

    ``A``: matriz aumentada del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(n+1), donde n es el número de incógnitas.

    ## Return

    ``solucion``: vector con la solución del sistema de ecuaciones lineales.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)
    #assert A.shape[0] == A.shape[1] - 1, "La matriz A debe ser de tamaño n-by-(n+1)."
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        for j in range(n):
            if j == i:
                continue  # no se elimina la fila del pivote
            
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

        A[i, :] = A[i, :] / A[i, i]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

        print(f"\n{A}")
    # # --- Sustitución hacia atrás
    # solucion = np.zeros(n)
    # solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    # for i in range(n - 2, -1, -1):
    #     suma = 0
    #     for j in range(i + 1, n):
    #         suma += A[i, j] * solucion[j]
    #     solucion[i] = (A[i, n] - suma) / A[i, i]

    return A

[01-13 17:54:37][INFO] 2026-01-13 17:54:37.237767


$A_1 = \begin{bmatrix} 1 & 3 & 4 \\ 2 & 1 & 3 \\ 4 & 2 & 1 \end{bmatrix}$

In [9]:
# Poner matriz aumentada a la derecha
n = len(A_1)
A_inv = np.hstack((A_1, np.eye(n)))

In [10]:
gauss_jordan(A_inv)

[01-13 17:54:37][INFO] 
[[  1.   3.   4.   1.   0.   0.]
 [  0.  -5.  -5.  -2.   1.   0.]
 [  0. -10. -15.  -4.   0.   1.]]
[01-13 17:54:37][INFO] 
[[ 1.   0.   1.  -0.2  0.6  0. ]
 [-0.   1.   1.   0.4 -0.2 -0. ]
 [ 0.   0.  -5.   0.  -2.   1. ]]
[01-13 17:54:37][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [-0.   1.   0.   0.4 -0.6  0.2]
 [-0.  -0.   1.  -0.   0.4 -0.2]]


array([[ 1. ,  0. ,  0. , -0.2,  0.2,  0.2],
       [-0. ,  1. ,  0. ,  0.4, -0.6,  0.2],
       [-0. , -0. ,  1. , -0. ,  0.4, -0.2]])

In [11]:
np.vstack((A_1, np.eye(n)))

array([[1., 3., 4.],
       [2., 1., 3.],
       [4., 2., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
_m_inv = gauss_jordan(A_inv)
_m_inv

[01-13 17:54:37][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [ 0.   1.   0.   0.4 -0.6  0.2]
 [ 0.   0.   1.  -0.   0.4 -0.2]]
[01-13 17:54:37][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [ 0.   1.   0.   0.4 -0.6  0.2]
 [ 0.   0.   1.  -0.   0.4 -0.2]]
[01-13 17:54:37][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [ 0.   1.   0.   0.4 -0.6  0.2]
 [ 0.   0.   1.  -0.   0.4 -0.2]]


array([[ 1. ,  0. ,  0. , -0.2,  0.2,  0.2],
       [ 0. ,  1. ,  0. ,  0.4, -0.6,  0.2],
       [ 0. ,  0. ,  1. , -0. ,  0.4, -0.2]])

In [13]:
_m_inv[:, n:]

array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [-0. ,  0.4, -0.2]])

# Comprobando respuesta

In [14]:
np.linalg.inv(np.array(A_1))

array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [ 0. ,  0.4, -0.2]])

$A_2 = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 1 & 4 \\5 & 6 & 0 \end{bmatrix}$

In [ ]:
A_2 = [[1,2,3],[0,1,4],[5,6,0]]

n = len(A_2)
A_inv = np.hstack((A_2, np.eye(n)))

_m_inv = gauss_jordan(A_inv)

_m_inv[:, n:]

[01-13 17:54:37][INFO] 
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]
[01-13 17:54:37][INFO] 
[[ 1.  0. -5.  1. -2.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]
[01-13 17:54:37][INFO] 
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

$A_3 = \begin{bmatrix} 4 & 2 & 1 \\ 2 & 1 & 3 \\ 1 & 3 & 4 \end{bmatrix}$

In [ ]:
A_3 = [[4,2,1],[2,1,3],[1,3,4]]

n = len(A_3)
A_inv = np.hstack((A_3, np.eye(n)))

_m_inv = gauss_jordan(A_inv)

_m_inv[:, n:]

[01-13 17:54:37][INFO] 
[[  1.   3.   4.   0.   0.   1.]
 [  0.  -5.  -5.   0.   1.  -2.]
 [  0. -10. -15.   1.   0.  -4.]]
[01-13 17:54:37][INFO] 
[[ 1.   0.   1.   0.   0.6 -0.2]
 [-0.   1.   1.  -0.  -0.2  0.4]
 [ 0.   0.  -5.   1.  -2.   0. ]]
[01-13 17:54:37][INFO] 
[[ 1.   0.   0.   0.2  0.2 -0.2]
 [-0.   1.   0.   0.2 -0.6  0.4]
 [-0.  -0.   1.  -0.2  0.4 -0. ]]


array([[ 0.2,  0.2, -0.2],
       [ 0.2, -0.6,  0.4],
       [-0.2,  0.4, -0. ]])

$A_4 = \begin{bmatrix} 2 & 4 & 6 & 1 \\ 4 & 7 & 5 & -6 \\ 2 & 5 & 18 & 10 \\ 6 & 12 & 38 & 16 \end{bmatrix}$

In [ ]:
A_4 = [[2, 4, 6, 1],[4, 7, 5, -6],[2,5,18,10],[6,12,38,16]]

n = len(A_4)
A_inv = np.hstack((A_4, np.eye(n)))

_m_inv = gauss_jordan(A_inv)

_m_inv[:, n:]

[01-13 17:54:37][INFO] 
[[ 1.   2.   3.   0.5  0.5  0.   0.   0. ]
 [ 0.  -1.  -7.  -8.  -2.   1.   0.   0. ]
 [ 0.   1.  12.   9.  -1.   0.   1.   0. ]
 [ 0.   0.  20.  13.  -3.   0.   0.   1. ]]
[01-13 17:54:37][INFO] 
[[  1.    0.  -11.  -15.5  -3.5   2.    0.    0. ]
 [ -0.    1.    7.    8.    2.   -1.   -0.   -0. ]
 [  0.    0.    5.    1.   -3.    1.    1.    0. ]
 [  0.    0.   20.   13.   -3.    0.    0.    1. ]]
[01-13 17:54:37][INFO] 
[[  1.    0.    0.  -13.3 -10.1   4.2   2.2   0. ]
 [ -0.    1.    0.    6.6   6.2  -2.4  -1.4  -0. ]
 [  0.    0.    1.    0.2  -0.6   0.2   0.2   0. ]
 [  0.    0.    0.    9.    9.   -4.   -4.    1. ]]
[01-13 17:54:37][INFO] 
[[ 1.          0.          0.          0.          3.2        -1.71111111
  -3.71111111  1.47777778]
 [-0.          1.          0.          0.         -0.4         0.53333333
   1.53333333 -0.73333333]
 [ 0.          0.          1.          0.         -0.8         0.28888889
   0.28888889 -0.02222222]
 [ 0.          0. 

array([[ 3.2       , -1.71111111, -3.71111111,  1.47777778],
       [-0.4       ,  0.53333333,  1.53333333, -0.73333333],
       [-0.8       ,  0.28888889,  0.28888889, -0.02222222],
       [ 1.        , -0.44444444, -0.44444444,  0.11111111]])

Calcule la descomposición LU para estas matrices y encuentre la solución para estos vectores de valores independientes 

In [ ]:
import numpy as np

# ####################################################################
def descomposicion_LU(A: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Realiza la descomposición LU de una matriz cuadrada A.
    [IMPORTANTE] No se realiza pivoteo.

    ## Parameters

    ``A``: matriz cuadrada de tamaño n-by-n.

    ## Return

    ``L``: matriz triangular inferior.

    ``U``: matriz triangular superior. Se obtiene de la matriz ``A`` después de aplicar la eliminación gaussiana.
    """

    A = np.array(
        A, dtype=float
    )  # convertir en float, porque si no, puede convertir como entero

    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."
    n = A.shape[0]

    L = np.zeros((n, n), dtype=float)

    for i in range(0, n):  # loop por columna

        # --- deterimnar pivote
        if A[i, i] == 0:
            raise ValueError("No existe solución única.")

        # --- Eliminación: loop por fila
        L[i, i] = 1
        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            L[j, i] = m

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")
    
    logging.info(f"\nMatriz U:\n{A}\n")
    logging.info(f"\nMatriz L:\n{L}\n")

    return L, A

# ####################################################################
def resolver_LU(L: np.ndarray, U: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante la descomposición LU.

    ## Parameters

    ``L``: matriz triangular inferior.

    ``U``: matriz triangular superior.

    ``b``: vector de términos independientes.

    ## Return

    ``solucion``: vector con la solución del sistema de ecuaciones lineales.

    """

    n = L.shape[0]

    # --- Sustitución hacia adelante
    logging.info("Sustitución hacia adelante")

    y = np.zeros((n, 1), dtype=float)

    y[0] = b[0] / L[0, 0]

    for i in range(1, n):
        suma = 0
        for j in range(i):
            suma += L[i, j] * y[j]
        y[i] = (b[i] - suma) / L[i, i]

    logging.info(f"\nVector y = \n{y}")

    # --- Sustitución hacia atrás
    logging.info("Sustitución hacia atrás")
    sol = np.zeros((n, 1), dtype=float)

    sol[-1] = y[-1] / U[-1, -1]

    for i in range(n - 2, -1, -1):
        #logging.info(f"i = {i}")
        suma = 0
        for j in range(i + 1, n):
            suma += U[i, j] * sol[j]
        # logging.info(f"suma = {suma}")
        # logging.info(f"U[i, i] = {U[i, i]}")
        #logging.info(f"y[i] = {y[i]}")
        sol[i] = (y[i] - suma) / U[i, i]

    logging.info(f"\nVector x = \n{sol}")
    return sol

$$b_1 = \begin{bmatrix} 1 \\ 2 \\ 4 \end{bmatrix}$$

Matriz $A_1$ con $b_1$

In [39]:
b_1 = [[1],[2],[4]]

L , U = descomposicion_LU(A_1)
resolver_LU(L, U, b_1)

[01-13 20:45:40][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 20:45:40][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 20:45:40][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 20:45:40][INFO] 
Matriz U:
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]

[01-13 20:45:40][INFO] 
Matriz L:
[[1. 0. 0.]
 [2. 1. 0.]
 [4. 2. 1.]]

[01-13 20:45:40][INFO] Sustitución hacia adelante
[01-13 20:45:40][INFO] 
Vector y = 
[[1.]
 [0.]
 [0.]]
[01-13 20:45:40][INFO] Sustitución hacia atrás
[01-13 20:45:40][INFO] 
Vector x = 
[[ 1.]
 [-0.]
 [-0.]]


array([[ 1.],
       [-0.],
       [-0.]])

Matriz $A_2$ con $b_1$

In [40]:
b_1 = [[1],[2],[4]]

L , U = descomposicion_LU(A_2)
resolver_LU(L, U, b_1)

[01-13 20:46:54][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 20:46:54][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 20:46:54][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 20:46:54][INFO] 
Matriz U:
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]

[01-13 20:46:54][INFO] 
Matriz L:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 5. -4.  1.]]

[01-13 20:46:54][INFO] Sustitución hacia adelante
[01-13 20:46:54][INFO] 
Vector y = 
[[1.]
 [2.]
 [7.]]
[01-13 20:46:54][INFO] Sustitución hacia atrás
[01-13 20:46:54][INFO] 
Vector x = 
[[ 32.]
 [-26.]
 [  7.]]


array([[ 32.],
       [-26.],
       [  7.]])

Matriz $A_3$ con $b_1$

In [41]:
b_1 = [[1],[2],[4]]

L , U = descomposicion_LU(A_3)
resolver_LU(L, U, b_1)

[01-13 20:47:30][INFO] 
[[4.   2.   1.  ]
 [0.   0.   2.5 ]
 [0.   2.5  3.75]]


ValueError: No existe solución única.

$$b_2 = \begin{bmatrix} 3 \\ -5 \\ 2 \end{bmatrix}$$

Matriz $A_1$ con $b_2$

In [42]:
b_2 = [[3],[-5],[2]]

L , U = descomposicion_LU(A_1)
resolver_LU(L, U, b_2)

[01-13 20:49:39][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 20:49:39][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 20:49:39][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 20:49:39][INFO] 
Matriz U:
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]

[01-13 20:49:39][INFO] 
Matriz L:
[[1. 0. 0.]
 [2. 1. 0.]
 [4. 2. 1.]]

[01-13 20:49:39][INFO] Sustitución hacia adelante
[01-13 20:49:39][INFO] 
Vector y = 
[[  3.]
 [-11.]
 [ 12.]]
[01-13 20:49:39][INFO] Sustitución hacia atrás
[01-13 20:49:39][INFO] 
Vector x = 
[[-1.2]
 [ 4.6]
 [-2.4]]


array([[-1.2],
       [ 4.6],
       [-2.4]])

Matriz $A_2$ con $b_2$

In [43]:
b_2 = [[3],[-5],[2]]

L , U = descomposicion_LU(A_2)
resolver_LU(L, U, b_2)

[01-13 20:50:18][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 20:50:18][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 20:50:18][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 20:50:18][INFO] 
Matriz U:
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]

[01-13 20:50:18][INFO] 
Matriz L:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 5. -4.  1.]]

[01-13 20:50:18][INFO] Sustitución hacia adelante
[01-13 20:50:18][INFO] 
Vector y = 
[[  3.]
 [ -5.]
 [-33.]]
[01-13 20:50:18][INFO] Sustitución hacia atrás
[01-13 20:50:18][INFO] 
Vector x = 
[[-152.]
 [ 127.]
 [ -33.]]


array([[-152.],
       [ 127.],
       [ -33.]])

Matriz $A_3$ con $b_2$

In [44]:
b_2 = [[3],[-5],[2]]

L , U = descomposicion_LU(A_3)
resolver_LU(L, U, b_2)

[01-13 20:51:12][INFO] 
[[4.   2.   1.  ]
 [0.   0.   2.5 ]
 [0.   2.5  3.75]]


ValueError: No existe solución única.

$$b_3 = \begin{bmatrix} 7 \\ 8 \\ -1 \end{bmatrix}$$

Matriz $A_1$ con $b_3$

In [47]:
b_3 = [[7],[8],[-1]]

L , U = descomposicion_LU(A_1)
resolver_LU(L, U, b_3)

[01-13 20:53:43][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 20:53:43][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 20:53:43][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 20:53:43][INFO] 
Matriz U:
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]

[01-13 20:53:43][INFO] 
Matriz L:
[[1. 0. 0.]
 [2. 1. 0.]
 [4. 2. 1.]]

[01-13 20:53:43][INFO] Sustitución hacia adelante
[01-13 20:53:43][INFO] 
Vector y = 
[[  7.]
 [ -6.]
 [-17.]]
[01-13 20:53:43][INFO] Sustitución hacia atrás
[01-13 20:53:43][INFO] 
Vector x = 
[[ 8.8817842e-16]
 [-2.2000000e+00]
 [ 3.4000000e+00]]


array([[ 8.8817842e-16],
       [-2.2000000e+00],
       [ 3.4000000e+00]])

Matriz $A_2$ con $b_3$

In [48]:
b_3 = [[7],[8],[-1]]

L , U = descomposicion_LU(A_2)
resolver_LU(L, U, b_3)

[01-13 20:54:01][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 20:54:01][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 20:54:01][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 20:54:01][INFO] 
Matriz U:
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]

[01-13 20:54:01][INFO] 
Matriz L:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 5. -4.  1.]]

[01-13 20:54:01][INFO] Sustitución hacia adelante
[01-13 20:54:01][INFO] 
Vector y = 
[[ 7.]
 [ 8.]
 [-4.]]
[01-13 20:54:01][INFO] Sustitución hacia atrás
[01-13 20:54:01][INFO] 
Vector x = 
[[-29.]
 [ 24.]
 [ -4.]]


array([[-29.],
       [ 24.],
       [ -4.]])

Matriz $A_3$ con $b_3$

In [49]:
b_3 = [[7],[8],[-1]]

L , U = descomposicion_LU(A_3)
resolver_LU(L, U, b_3)

[01-13 20:54:18][INFO] 
[[4.   2.   1.  ]
 [0.   0.   2.5 ]
 [0.   2.5  3.75]]


ValueError: No existe solución única.

$$b_4 = \begin{bmatrix} 1 \\ 2 \\ 4 \\ 5 \end{bmatrix}$$

Matriz $A_4$ con $b_4$

In [50]:
b_4 = [[1],[2],[4],[5]]

L , U = descomposicion_LU(A_4)
resolver_LU(L, U, b_4)

[01-13 20:56:00][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 20:56:00][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 20:56:00][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 20:56:00][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 20:56:00][INFO] 
Matriz U:
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]

[01-13 20:56:00][INFO] 
Matriz L:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1. -1.  1.  0.]
 [ 3. -0.  4.  1.]]

[01-13 20:56:00][INFO] Sustitución hacia adelante
[01-13 20:56:00][INFO] 
Vector y = 
[[  1.]
 [  0.]
 [  3.]
 [-10.]]
[01-13 20:56:00][INFO] Sustitución hacia atrás
[01-13 20:56:00][INFO] 
Vector x = 
[[-7.67777778]
 [ 3.13333333]
 [ 0.82222222]
 [-1.11111111]]


array([[-7.67777778],
       [ 3.13333333],
       [ 0.82222222],
       [-1.11111111]])

$$b_5 = \begin{bmatrix} 3 \\ -5 \\ 2 \\ 6 \end{bmatrix}$$

Matriz $A_4$ con $b_5$

In [51]:
b_4 = [[3],[-5],[2],[6]]

L , U = descomposicion_LU(A_4)
resolver_LU(L, U, b_4)

[01-13 20:57:03][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 20:57:03][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 20:57:03][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 20:57:03][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 20:57:03][INFO] 
Matriz U:
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]

[01-13 20:57:03][INFO] 
Matriz L:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1. -1.  1.  0.]
 [ 3. -0.  4.  1.]]

[01-13 20:57:03][INFO] Sustitución hacia adelante
[01-13 20:57:03][INFO] 
Vector y = 
[[  3.]
 [-11.]
 [-12.]
 [ 45.]]
[01-13 20:57:03][INFO] Sustitución hacia atrás
[01-13 20:57:03][INFO] 
Vector x = 
[[19.6]
 [-5.2]
 [-3.4]
 [ 5. ]]


array([[19.6],
       [-5.2],
       [-3.4],
       [ 5. ]])

$$b_6 = \begin{bmatrix} 7 \\ 8 \\ -1 \\ 0 \end{bmatrix}$$

Matriz $A_4$ con $b_6$

In [52]:
b_4 = [[7],[8],[-1],[0]]

L , U = descomposicion_LU(A_4)
resolver_LU(L, U, b_4)

[01-13 20:57:45][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 20:57:45][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 20:57:45][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 20:57:45][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 20:57:46][INFO] 
Matriz U:
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]

[01-13 20:57:46][INFO] 
Matriz L:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1. -1.  1.  0.]
 [ 3. -0.  4.  1.]]

[01-13 20:57:46][INFO] Sustitución hacia adelante
[01-13 20:57:46][INFO] 
Vector y = 
[[  7.]
 [ -6.]
 [-14.]
 [ 35.]]
[01-13 20:57:46][INFO] Sustitución hacia atrás
[01-13 20:57:46][INFO] 
Vector x = 
[[12.42222222]
 [-0.06666667]
 [-3.57777778]
 [ 3.88888889]]


array([[12.42222222],
       [-0.06666667],
       [-3.57777778],
       [ 3.88888889]])